### PR TITLE
Using Label text for images

### PR DESCRIPTION
**Pull request by Malleas**
Added ability to use a clickAfter function that uses the label text of an image based on its relationship to the object that precedes it.

### CODE REVIEW

**Comment by mfulton26** [comment]
hmmm, this appears to add the ability to click things by "className" which are not visible to the user...

**Comment by Malleas** [comment]
Correct, the issue we have is that there is an image that is used over and over again (help text icon) that has text that precedes it.  Using the webAutomator.after("String") doesn't work if we're using multiple interactions on a single page.  Edge case for clicking on an img rather than actual text.

**Comment by mfulton26** [comment]
I think there are a couple ways of dealing with this but treating a class name such as "help-text-icon" as WebAutomator context defeats the purpose of the API as its goal is to allow users to interact with elements through _rendered_ context (things actually visible to them, e.g. text, images, titles, inputs, etc.).

I suggest one of the following:

1. Use Selenium WebDriver directly to find your element by className:
    ```js
    await webDriver.findElement({css: '.help-text-icon-class-name'}).click();
    ```
2. Add support to WebAutomator for detecting and not ignoring (as it currently does) images. WebAutomator currently exposes the [`title`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title) and `value` attributes as rendered text but what should this look like for an image (non-textual)? Using the [`alt`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#Authoring_meaningful_alternate_descriptions) attribute could be appropriate but it is never actually _rendered_ unless the image is not found (although it is _dictated_ when using a screen reader). The `src` attribute could be used but still seems like a hack and finding an element using traditional WebDriver locators seems more appropriate. I believe in WebAutomator this would require including a base64 encoding of a PNG representing the rendered image (taking into account the scaling and transformations to the original image using CSS, etc.). This base64 encoded image could then be included with the data sent to the client and used in search context. e.g.:

    ```js
    // defined somewhere in set-up and captured previously, possibly different for different browsers
    const HELP_TEXT_ICON = {src:  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAaQAAAGkCAIAAADxLsZiAAAF9ElEQVR4nOzXUa3bQBBA0b7KFEIxEAIiEEzRPwuhH5UKIHJ3lb3nEJiRRnsTH2OMXwC7+716AYAZxA5IEDsgQeyABLEDEsQOSBA7IEHsgASxAxLEDkgQOyBB7IAEsQMSxA5IEDsgQeyABLEDEsQOSBA7IEHsgASxAxLEDkgQOyBB7IAEsQMSxA5IEDsgQeyABLEDEsQOSBA7IEHsgASxAxLEDkg4Vi/wxc73tXqF+z1fj9Ur3MmN+Mc/OyBB7IAEsQMSxA5IEDsgQeyABLEDEsQOSBA7IEHsgASxAxLEDkgQOyBB7IAEsQMSxA5IEDsgQeyABLEDEsQOSBA7IEHsgASxAxLEDkgQOyBB7IAEsQMSxA5IEDsgQeyABLEDEsQOSBA7IEHsgASxAxLEDkgQOyBB7IAEsQMSxA5IEDsgQeyABLEDEsQOSBA7IEHsgASxAxLEDkgQOyBB7IAEsQMSxA5IEDsgQeyABLEDEsQOSBA7IEHsgASxAxLEDkgQOyBB7IAEsQMSxA5IEDsgQeyABLEDEsQOSBA7IOGYNul8X9Nmwcb2e0rP12PClHmx29KcI/Gx/Q60X+mm8RkLJIgdkCB2QILYAQliBySIHZAgdkCC2AEJYgckiB2QIHZAgtgBCWIHJIgdkCB2QILYAQliBySIHZAgdkCC2AEJYgckiB2QIHZAgtgBCWIHJIgdkCB2QILYAQliBySIHZAgdkCC2AEJYgckiB2QIHZAgtgBCWIHJIgdkCB2QILYAQliBySIHZAgdkCC2AEJYgckiB2QIHZAgtgBCWIHJIgdkCB2QILYAQliBySIHZAgdkCC2AEJYgckiB2QIHZAgtgBCWIHJIgdkCB2QILYAQliBySIHZAgdkCC2AEJx+oFvtv5vlavcLPn67F6hTvtdyA+Ni92m70iD4lV9ntKc/iMBRLEDkgQOyBB7IAEsQMSxA5IEDsgQeyABLEDEsQOSBA7IEHsgASxAxLEDkgQOyBB7IAEsQMSxA5IEDsgQeyABLEDEsQOSBA7IEHsgASxAxLEDkgQOyBB7IAEsQMSxA5IEDsgQeyABLEDEsQOSBA7IEHsgASxAxLEDkgQOyBB7IAEsQMSxA5IEDsgQeyABLEDEsQOSBA7IEHsgASxAxLEDkgQOyBB7IAEsQMSxA5IEDsgQeyABLEDEsQOSBA7IEHsgASxAxLEDkgQOyBB7IAEsQMSxA5IEDsgQeyABLEDEsQOSBA7IEHsgASxAxLEDkgQOyBB7IAEsQMSxA5IEDsgQeyABLEDEsQOSBA7IEHsgASxAxLEDkgQOyBB7IAEsQMSxA5IEDsgQeyABLEDEsQOSBA7IEHsgASxAxLEDkgQOyBB7IAEsQMSxA5IEDsgQeyABLEDEsQOSBA7IEHsgASxAxLEDkgQOyBB7IAEsQMSxA5IEDsgQeyABLEDEsQOSBA7IEHsgASxAxLEDkgQOyBB7IAEsQMSxA5IEDsgQeyABLEDEsQOSBA7IEHsgASxAxLEDkgQOyBB7IAEsQMSxA5I+BljzJl0vq85g4Dv8nw9Jkw5JszY2JwjTbPlD5Ib8ZfPWCBB7IAEsQMSxA5IEDsgQeyABLEDEsQOSBA7IEHsgASxAxLEDkgQOyBB7IAEsQMSxA5IEDsgQeyABLEDEsQOSBA7IEHsgASxAxLEDkgQOyBB7IAEsQMSxA5IEDsgQeyABLEDEsQOSBA7IEHsgASxAxLEDkgQOyBB7IAEsQMSxA5IEDsgQeyABLEDEsQOSBA7IEHsgASxAxLEDkgQOyBB7IAEsQMSxA5IEDsgQeyABLEDEsQOSBA7IEHsgASxAxLEDkgQOyBB7IAEsQMSxA5IEDsgQeyABLEDEsQOSBA7IOFnjLF6B4D/zj87IEHsgASxAxLEDkgQOyBB7IAEsQMSxA5IEDsgQeyABLEDEsQOSBA7IEHsgASxAxLEDkgQOyBB7IAEsQMSxA5IEDsgQeyABLEDEsQOSBA7IEHsgASxAxLEDkgQOyBB7IAEsQMSxA5IEDsg4U8AAAD//8PmLMXCSgcDAAAAAElFTkSuQmCC'};

    // in actual code reference {src: <dataimageurl>} to locate said image
    await webAutomator.click(HELP_TEXT_ICON);
    ```

    A downside with this approach is that the image must be rendered exactly as it was previously (which may be a upside depending on what you're trying to test). The "rendered" image may also be slightly different browser to browser as they use different rendering engines.

3. I think the best solution would be to add support to WebAutomator to take a `WebElement` instance wherever it supports taking a `String` or `RegExp` to find elements. Earlier implementations of WebAutomator and similar tooling supported such and this allows you to use an element found via `WebDriver.findElement` as context in WebAutomator. e.g.:

    ```js
    const helpTextIcon = await webDriver.findElement({css: '.help-text-icon-class-name'});
    await webAutomator.after(helpTextIcon, context => {/*do something after the icon*/});
    ```

    This can be used in conjunction with other options and shouldn't be too difficult to add to WebAutomator as WebElement instances are comparable by their IDs so elements returned internally to WebAutomator can be matched against elements passed through to `click`, `after`, `set`, etc.

    By itself this option does not add support for locating images to WebAutomator but it would add support to use it in context for locating other elements as well as clicking them, etc.

For the quickest win I suggest using `WebDriver` directly (the instance being used by a `WebAutomator` instance can be accessed via `webAutomator.webDriver`.

**Comment by darkhorse93** [comment]
Hi @mfulton26, Currently webautomator doesn't support interacting with images/image links on a webpage. We can work towards adding such capability. One approach would be we can explore using [textract](https://www.npmjs.com/package/textract) or similar OCR based APIs to extract (best)approximate text information from select images(as a user on webpage)  and put it as label text to the element, so that we can interact with images.

Please share, if we can try any other approach with which we can include images in webautomator's scope.

**Comment by mfulton26** [comment]
Thank you for your reply @darkhorse93. The first problem is simply adding image data to `src/remote/content.js`. i.e. We need to add a way to serialize over the wire a string representation of an image. I believe a base64 encoded string of a PNG that represents the rendered image would be the best approach. Any OCR analysis done to the image could be done on the client-side (and not the remote, i.e. the browser).

Once we know what an image should _look_ like we can then "dump" said representation and use it in our tests (probably setting up some kind of file to store these in instead of cluttering code with really long base64 encoded PNG images).

Many images do not contain text (such as a help icon that is simply a question mark in a circle, OCR would likely not extract `"?"` from such a low resolution image).

This is all possible, in fact I had some code at one point that took into account most CSS transformations on an image. I don't recall if it had a performance impact as the data being sent from the remote back to the WebAutomator client will be significantly larger.

**Comment by darkhorse93** [comment]
Let me know if I got it right. below is my understanding.

Execute getContentBundle on browser > get content array(with img as base64 data) > filter for images > do an ocr analysis, extract and set it as label text to that element > work/interact with desired element on content array...

**Comment by mfulton26** [comment]
Somewhat, `getContentBundle` does not currently dump representations of rendered images so that needs to be added first.

Once the content payload contains rendered image data then we can do whatever we want with them. I don't see WebAutomator in its current state using OCR but I could see creating an extension point or something to allow supporting such. I'm not sure OCR is really needed though, a base64 encoded PNG is just a string of characters so we can match against exact images.

I still feel that the simplest thing to do is to find images using traditional WebDriver locators (e.g. by css, xpath, id, etc.). It is far simpler and it avoids the issue where images may be rendered slightly different on different browsers and/or operating systems but if what you are after to test is indeed that images look a certain way then adding support for locating content based on rendered image bytes seems the way to go (which is what we're discussing doing here).

**Comment by mfulton26** [comment]
I'm so glad I captured some code I had played with months ago. Please see https://github.com/mfulton26/webautomator/issues/10.

**Comment by mfulton26** [comment]
Once #10 is implemented the flow would be:
1. Execute getContentBundle on browser
2. Search returned content for an  encoded image (passing in `{img: 'base64encodedData'}` or something similar instead of simply `'label text'`)
3. Continue with existing functionality (keep searching sub context, click something, set some value on an input that comes after it, etc., etc.)

**Pull request closed without merging**
